### ISSUE TITLE
Fix: If user is logged in he should not be able to see the home page for unlogged users.

### ISSUE THREAD

**Issue by vmnog** [status-451/plotwist#102]
If user is logged in and he tries to access https://plotwist.app/pt-BR he should be redirect to https://plotwist.app/pt-BR/home until his session expires or he logouts.

One of the reasons of that is that it does not make sense to offer the membership plan if user already has the membership plan.
![image](https://github.com/status-451/plotwist/assets/43258815/9c453a9b-0115-4cca-89b5-cc4812260205)
In this image the membership plan is being ofered to the user even though he is already logged in and he is a member.

**Comment by lui7henrique** [comment]
LGTM! I'll move this issue for currently Iterate.

**Comment by lui7henrique** [comment]
Resolved: https://github.com/status-451/plotwist/commit/e6d3611d005ccdcaa4aa1bc27a363fa23d058a2d
